/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onikami_antelope_SigningRequestCallbackManager */

#ifndef _Included_com_onikami_antelope_SigningRequestCallbackManager
#define _Included_com_onikami_antelope_SigningRequestCallbackManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onikami_antelope_SigningRequestCallbackManager
 * Method:    callbackReceived
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_onikami_antelope_SigningRequestCallbackManager_callbackReceived
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
