/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onikami_antelope_SingningRequestCallbackManager */

#ifndef _Included_com_onikami_antelope_SingningRequestCallbackManager
#define _Included_com_onikami_antelope_SingningRequestCallbackManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onikami_antelope_SingningRequestCallbackManager
 * Method:    callbackReceived
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_onikami_antelope_SingningRequestCallbackManager_callbackReceived
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
